'use client';

// import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import axios from 'axios';
import { useState } from 'react';
import Spinner from './components/reusable/spinner/spinner';
import Alert from './components/reusable/alert/alert';
import { useRouter } from 'next/navigation';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  const [loader, setLoader] = useState(false);
  const [{ isError, message }, setIsError] = useState({
    isError: false,
    message: '',
  });

  async function handleLogout() {
    try {
      setLoader(true);
      const response = await axios.get('/api/users/logout', {});
      console.log(response);
      response?.data?.success && router.push('/login');
    } catch (error: unknown) {
      if (axios.isAxiosError(error) && error.response) {
        const errorMessage =
          error.response.data?.error || 'Sorry Something went wrong';
        console.log(errorMessage);
        setIsError({ isError: true, message: errorMessage });
      } else if (error instanceof Error) {
        console.log(error.message);
        setIsError({ isError: true, message: error.message });
      } else {
        console.log('Unknown error', error);
        setIsError({ isError: true, message: 'Sorry Something went wrong' });
      }
    } finally {
      setLoader(false);
    }
  }

  return (
    <html lang='en'>
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className='bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 text-white py-4 shadow-2xl sticky top-0 z-50 backdrop-blur-sm bg-opacity-95'>
          <div className='max-w-7xl mx-auto px-6 flex justify-between items-center'>
            <div className='flex items-center space-x-3'>
              <div className='w-10 h-10 bg-white bg-opacity-20 rounded-xl flex items-center justify-center backdrop-blur-sm'>
                <svg className='w-6 h-6 text-white' fill='none' stroke='currentColor' viewBox='0 0 24 24'>
                  <path strokeLinecap='round' strokeLinejoin='round' strokeWidth={2} d='M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z' />
                </svg>
              </div>
              <h1 className='text-2xl font-bold tracking-wide bg-gradient-to-r from-white to-blue-100 bg-clip-text text-transparent'>
                TaskFlow
              </h1>
            </div>
            <nav className='hidden md:flex items-center space-x-6'>
              <a className='flex items-center space-x-2 text-white hover:text-blue-200 transition-colors duration-200 group'>
                <svg className='w-4 h-4 group-hover:scale-110 transition-transform' fill='none' stroke='currentColor' viewBox='0 0 24 24'>
                  <path strokeLinecap='round' strokeLinejoin='round' strokeWidth={2} d='M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6' />
                </svg>
                <span className='text-sm font-medium'>Home</span>
              </a>
              <a className='flex items-center space-x-2 text-white hover:text-blue-200 transition-colors duration-200 group'>
                <svg className='w-4 h-4 group-hover:scale-110 transition-transform' fill='none' stroke='currentColor' viewBox='0 0 24 24'>
                  <path strokeLinecap='round' strokeLinejoin='round' strokeWidth={2} d='M13 10V3L4 14h7v7l9-11h-7z' />
                </svg>
                <span className='text-sm font-medium'>Features</span>
              </a>
              <a className='flex items-center space-x-2 text-white hover:text-blue-200 transition-colors duration-200 group'>
                <svg className='w-4 h-4 group-hover:scale-110 transition-transform' fill='none' stroke='currentColor' viewBox='0 0 24 24'>
                  <path strokeLinecap='round' strokeLinejoin='round' strokeWidth={2} d='M3 8l7.89 4.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z' />
                </svg>
                <span className='text-sm font-medium'>Contact</span>
              </a>
              <button
                className='hidden md:flex items-center space-x-2 bg-red-500 hover:bg-red-600 text-white font-semibold py-2 px-4 rounded-xl transition-all duration-300 shadow-lg hover:shadow-xl transform hover:scale-105 group'
                onClick={handleLogout}
              >
                <svg className='w-4 h-4 group-hover:rotate-12 transition-transform' fill='none' stroke='currentColor' viewBox='0 0 24 24'>
                  <path strokeLinecap='round' strokeLinejoin='round' strokeWidth={2} d='M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1' />
                </svg>
                <span>Logout</span>
              </button>
            </nav>

            {/* Mobile Menu Button */}
            <div className='md:hidden flex items-center space-x-3'>
              <button
                className='flex items-center space-x-2 bg-red-500 hover:bg-red-600 text-white font-semibold py-2 px-3 rounded-xl transition-all duration-300 shadow-lg hover:shadow-xl transform hover:scale-105 group'
                onClick={handleLogout}
              >
                <svg className='w-4 h-4 group-hover:rotate-12 transition-transform' fill='none' stroke='currentColor' viewBox='0 0 24 24'>
                  <path strokeLinecap='round' strokeLinejoin='round' strokeWidth={2} d='M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1' />
                </svg>
                <span className='hidden sm:inline'>Logout</span>
              </button>
            </div>
          </div>
        </header>
        <main className='px-4 sm:px-6 lg:px-8 py-6 sm:py-8 bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 min-h-screen relative overflow-hidden'>
          {/* Background Pattern */}
          <div className='absolute inset-0 bg-[url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%239C92AC' fill-opacity='0.05'%3E%3Ccircle cx='30' cy='30' r='2'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")] opacity-20'></div>
        <div className='relative z-10'>
          <Spinner loading={loader} />
          {isError && (
            <div className='flex justify-center'>
              <Alert
                message={message}
                type='error'
                style={{ minWidth: '350px' }}
                className='mb-7 text-center'
              />
            </div>
          )}
          {children}
        </div>
      </main>
      <footer className='bg-gradient-to-r from-slate-900 via-slate-800 to-slate-900 text-slate-300 py-12 border-t border-slate-700'>
        <div className='max-w-7xl mx-auto px-6'>
          <div className='grid grid-cols-1 md:grid-cols-4 gap-8 mb-8'>
            <div className='space-y-4'>
              <div className='flex items-center space-x-3'>
                <div className='w-8 h-8 bg-gradient-to-r from-indigo-500 to-purple-500 rounded-lg flex items-center justify-center'>
                  <svg className='w-5 h-5 text-white' fill='none' stroke='currentColor' viewBox='0 0 24 24'>
                    <path strokeLinecap='round' strokeLinejoin='round' strokeWidth={2} d='M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z' />
                  </svg>
                </div>
                <h3 className='text-xl font-bold text-white'>TaskFlow</h3>
              </div>
              <p className='text-slate-400 text-sm leading-relaxed'>
                Your ultimate task management solution. Organize, prioritize, and achieve your goals with ease.
              </p>
              <div className='flex space-x-4'>
                <a className='w-8 h-8 bg-slate-700 hover:bg-indigo-500 rounded-lg flex items-center justify-center transition-colors duration-200 group'>
                  <svg className='w-4 h-4 text-slate-300 group-hover:text-white' fill='currentColor' viewBox='0 0 24 24'>
                    <path d='M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z' />
                  </svg>
                </a>
                <a className='w-8 h-8 bg-slate-700 hover:bg-indigo-500 rounded-lg flex items-center justify-center transition-colors duration-200 group'>
                  <svg className='w-4 h-4 text-slate-300 group-hover:text-white' fill='currentColor' viewBox='0 0 24 24'>
                    <path d='M22.46 6c-.77.35-1.6.58-2.46.69.88-.53 1.56-1.37 1.88-2.38-.83.5-1.75.85-2.72 1.05C18.37 4.5 17.26 4 16 4c-2.35 0-4.27 1.92-4.27 4.29 0 .34.04.67.11.98C8.28 9.09 5.11 7.38 3 4.79c-.37.63-.58 1.37-.58 2.15 0 1.49.75 2.81 1.91 3.56-.71 0-1.37-.2-1.95-.5v.03c0 2.08 1.48 3.82 3.44 4.21a4.22 4.22 0 0 1-1.93.07 4.28 4.28 0 0 0 4 2.98 8.521 8.521 0 0 1-5.33 1.84c-.34 0-.68-.02-1.02-.06C3.44 20.29 5.7 21 8.12 21 16 21 20.33 14.46 20.33 8.79c0-.19 0-.37-.01-.56.84-.6 1.56-1.36 2.14-2.23z' />
                  </svg>
                </a>
                <a className='w-8 h-8 bg-slate-700 hover:bg-indigo-500 rounded-lg flex items-center justify-center transition-colors duration-200 group'>
                  <svg className='w-4 h-4 text-slate-300 group-hover:text-white' fill='currentColor' viewBox='0 0 24 24'>
                    <path d='M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z' />
                  </svg>
                </a>
              </div>
            </div>

            <div className='space-y-4'>
              <h4 className='text-lg font-semibold text-white'>Product</h4>
              <ul className='space-y-2 text-sm'>
                <li><a className='text-slate-400 hover:text-white transition-colors duration-200 cursor-pointer'>Features</a></li>
                <li><a className='text-slate-400 hover:text-white transition-colors duration-200 cursor-pointer'>Pricing</a></li>
                <li><a className='text-slate-400 hover:text-white transition-colors duration-200 cursor-pointer'>API</a></li>
                <li><a className='text-slate-400 hover:text-white transition-colors duration-200 cursor-pointer'>Integrations</a></li>
              </ul>
            </div>

            <div className='space-y-4'>
              <h4 className='text-lg font-semibold text-white'>Company</h4>
              <ul className='space-y-2 text-sm'>
                <li><a className='text-slate-400 hover:text-white transition-colors duration-200 cursor-pointer'>About</a></li>
                <li><a className='text-slate-400 hover:text-white transition-colors duration-200 cursor-pointer'>Blog</a></li>
                <li><a className='text-slate-400 hover:text-white transition-colors duration-200 cursor-pointer'>Careers</a></li>
                <li><a className='text-slate-400 hover:text-white transition-colors duration-200 cursor-pointer'>Contact</a></li>
              </ul>
            </div>

            <div className='space-y-4'>
              <h4 className='text-lg font-semibold text-white'>Support</h4>
              <ul className='space-y-2 text-sm'>
                <li><a className='text-slate-400 hover:text-white transition-colors duration-200 cursor-pointer'>Help Center</a></li>
                <li><a className='text-slate-400 hover:text-white transition-colors duration-200 cursor-pointer'>Documentation</a></li>
                <li><a className='text-slate-400 hover:text-white transition-colors duration-200 cursor-pointer'>Status</a></li>
                <li><a className='text-slate-400 hover:text-white transition-colors duration-200 cursor-pointer'>Community</a></li>
              </ul>
            </div>
          </div>

          <div className='border-t border-slate-700 pt-8 flex flex-col md:flex-row justify-between items-center'>
            <p className='text-slate-400 text-sm mb-4 md:mb-0'>
              &copy; 2025 TaskFlow. All rights reserved. Built with ❤️ using Next.js
            </p>
            <div className='flex space-x-6 text-sm'>
              <a className='text-slate-400 hover:text-white transition-colors duration-200 cursor-pointer'>Privacy Policy</a>
              <a className='text-slate-400 hover:text-white transition-colors duration-200 cursor-pointer'>Terms of Service</a>
              <a className='text-slate-400 hover:text-white transition-colors duration-200 cursor-pointer'>Cookie Policy</a>
            </div>
          </div>
        </div>
      </footer>
    </body>
    </html >
  );
}
