'use client';

// import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import axios from 'axios';
import { useState } from 'react';
import Spinner from './components/reusable/spinner/spinner';
import Alert from './components/reusable/alert/alert';
import { useRouter } from 'next/navigation';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  const [loader, setLoader] = useState(false);
  const [{ isError, message }, setIsError] = useState({
    isError: false,
    message: '',
  });

  async function handleLogout() {
    try {
      setLoader(true);
      const response = await axios.get('/api/users/logout', {});
      console.log(response);
      response?.data?.success && router.push('/login');
    } catch (error: unknown) {
      if (axios.isAxiosError(error) && error.response) {
        const errorMessage =
          error.response.data?.error || 'Sorry Something went wrong';
        console.log(errorMessage);
        setIsError({ isError: true, message: errorMessage });
      } else if (error instanceof Error) {
        console.log(error.message);
        setIsError({ isError: true, message: error.message });
      } else {
        console.log('Unknown error', error);
        setIsError({ isError: true, message: 'Sorry Something went wrong' });
      }
    } finally {
      setLoader(false);
    }
  }

  return (
    <html lang='en'>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className='bg-gradient-to-r from-slate-800 to-slate-600 text-white py-6 shadow-lg sticky top-0 z-50'>
          <div className='max-w-6xl mx-auto px-4 flex justify-between items-center'>
            <h1 className='text-2xl font-bold tracking-wide hover:text-blue-300 transition-colors duration-200'>
              CozyApp
            </h1>
            <nav className='space-x-6 text-sm font-medium'>
              <a>#Home</a>
              <a> #Features</a>
              <a>contact</a>
              <button
                className='bg-red-600 hover:bg-red-700 text-white font-semibold py-2 px-4 rounded transition duration-300 shadow-md'
                onClick={handleLogout}
              >
                Logout
              </button>
            </nav>
          </div>
        </header>
        <main className='px-5 py-7 bg-gradient-to-br from-slate-900 via-slate-800 to-slate-700 min-h-screen'>
          <Spinner loading={loader} />
          {isError && (
            <div className='flex justify-center'>
              <Alert
                message={message}
                type='error'
                style={{ minWidth: '350px' }}
                className='mb-7 text-center'
              />
            </div>
          )}
          {children}
        </main>
        <footer className='bg-slate-950 text-slate-200 py-6 border-t border-slate-700'>
          <div className='max-w-6xl mx-auto px-4 flex flex-col md:flex-row justify-between items-center text-sm'>
            <p className='mb-2 md:mb-0'>
              &copy; 2025 CozyApp. All rights reserved.
            </p>
            <div className='space-x-4'>
              <a>#Privacy Policy</a>
              <a>#Terms of Service</a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
